import { Component, CUSTOM_ELEMENTS_SCHEMA, OnInit } from '@angular/core';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { ProductService } from '../product.service';
import { ReviewService } from '../review.service';
import { OrderItemService } from '../order-item.service';
import { CommonModule } from '@angular/common';
import { OrderItem } from '../order-item';
import { UserService } from '../user.service';
import { Product } from '../product';  // Import the Product model
import { FormsModule } from '@angular/forms';
import { Review } from '../review';

@Component({
  selector: 'app-product-details',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [CommonModule, RouterModule,FormsModule],
  templateUrl: './product-details.component.html',
  styleUrls: ['./product-details.component.css']
})
export class ProductDetailsComponent implements OnInit {
  product: Product | null = null; // Updated type
  reviews: any[] = [];
  newReview = { username: '', rating: 1, comment: '', reviewDate: new Date() };


  constructor(
    private route: ActivatedRoute,
    private productService: ProductService,
    private reviewService: ReviewService,
    private orderItemService: OrderItemService,
    private userService: UserService
  ) {}

  ngOnInit(): void {
    const productId = this.route.snapshot.paramMap.get('id');
    if (productId) {
      this.productService.getProductById(productId).subscribe({
        next: (product: Product) =>{ this.product = product;
          this.loadReviews(productId);
        },
        error: (err) => console.error('Error fetching product details:', err)
      });

      this.productService.getReviewsByProductId(productId).subscribe({
        next: (reviews) => this.reviews = reviews,
        error: (err) => console.error('Error fetching reviews:', err)
      });
      this.newReview.username = localStorage.getItem('username') || '';

    }
  }

  loadReviews(productId: string): void {
    this.productService.getReviewsByProductId(productId).subscribe(reviews => {
      this.reviews = reviews;
    });
  }
 
  addToCart(): void {
    // Retrieve the current cart from localStorage
    let cart = JSON.parse(localStorage.getItem('cart') || '[]');

    // Check if the product is already in the cart
    const existingItemIndex = cart.findIndex((item: any) => item.productId === this.product?.id);

    if (existingItemIndex >= 0) {
      // If the product already exists, update its quantity
      cart[existingItemIndex].quantity += 1;
    } else {
      // If the product does not exist, add it to the cart
      const orderItem: OrderItem = {
        id: '', // id will be generated by the backend
        orderId: '', // orderId will be associated when creating the order
        productId: this.product?.id || '',
        productName: this.product?.name || '',
        price: this.product?.price || 0,
        quantity: 1 // Default quantity
      };
      cart.push(orderItem);
    }

    // Save the updated cart back to localStorage
    localStorage.setItem('cart', JSON.stringify(cart));
  }
  
  submitReview(): void {
    if (!this.product) {
      console.error('Product details are not loaded.');
      alert('Product details are not loaded.');
      return;
    }
  
    // Ensure username is not null or undefined, default to an empty string if it is.
    const username = localStorage.getItem('username') || '';
  
    // Only proceed if username is not an empty string
    if (!username) {
      alert('Username is not available. Please log in.');
      return;
    }
  
    const review: Review = {
      productId: this.product.id,
      userId: username, // Guaranteed to be a non-empty string now
      rating: this.newReview.rating,
      comment: this.newReview.comment,
      reviewDate: new Date() // Use the Date object directly if your backend expects a date
    };
  
    this.reviewService.createReview(review).subscribe({
      next: (reviewResponse) => {
        this.reviews.push(reviewResponse);
        this.newReview = { username: '', rating: 1, comment: '', reviewDate: new Date() }; // Reset the form
        alert('Review submitted successfully!');
      },
      error: (error) => {
        console.error('Failed to add review:', error);
        alert('Failed to add review: ' + error.message);
      }
    });
  }

  isLowStock() {
    return this.product && this.product.stockQuantity < 5;
  }
  
  signOut(): void {
    // Implement sign-out logic
    this.userService.signOut();
  }
}
